- task: BatchScript@1
  displayName: Run npm install
  inputs:
    filename: '[% base_dir %]/npm-install.cmd'
[%- IF prepare_only %]
- task: BatchScript@1
  displayName: Create vsts project 
  inputs:
    filename: '[% base_dir %]/prepare.cmd'
[%- ELSE %]
- task: BatchScript@1
  displayName:  Remove build directory
  inputs:
    filename: '[% base_dir %]/clean-build-dir.cmd'
- task: BatchScript@1
  displayName:  Add windows plaform
  inputs:
    filename: '[% base_dir %]/platform-add.cmd'
- task: CmdLine@1
  displayName: Set package version
  inputs:
    filename: perl
    arguments: '[% base_dir %]/set-version.pl' "\$(Build.BuildId)"
    workingDirectory: "\$(Build.SourcesDirectory)"
- task: BatchScript@1
  displayName:  Build package
  inputs:
    filename: '[% base_dir %]/build.cmd'
[%- END %]

