- task: BatchScript@1
  displayName: Run npm install
  inputs:
    filename: '[% base_dir %]/npm-install.cmd'
- task: BatchScript@1
  displayName: Run npm install cordova
  inputs:
    filename: '[% base_dir %]/npm-install-cordova.cmd'
- task: BatchScript@1
  displayName: Run npm install ionic
  inputs:
    filename: '[% base_dir %]/npm-install-ionic.cmd'
- task: CmdLine@1
  displayName: Create www dir
  inputs:
    filename: perl
    arguments: -e "mkdir www"
    workingDirectory: "\$(Build.SourcesDirectory)"
[%- IF prepare_only %]
- task: BatchScript@1
  displayName: Create vsts project 
  inputs:
    filename: '[% base_dir %]/prepare.cmd'
[%- ELSE %]
- task: BatchScript@1
  displayName: Run npm install cordova-set-version
  inputs:
    filename: '[% base_dir %]/npm-install-cordova-set-version.cmd'
- task: CmdLine@1
  displayName: Remove build directory
  inputs:
    filename: perl
    arguments: [% base_dir %]/remove-old-packages.pl platforms\windows\AppPackages\
    workingDirectory: "\$(Build.SourcesDirectory)"
- task: BatchScript@1
  displayName:  Add windows plaform
  inputs:
    filename: '[% base_dir %]/platform-add.cmd'
- task: CmdLine@1
  displayName: Set package version
  inputs:
    filename: perl
    arguments: [% base_dir %]/set-version.pl "\$(Build.BuildId)"
    workingDirectory: "\$(Build.SourcesDirectory)"
- task: CmdLine@1
  displayName: Configure
  inputs:
    filename: perl
    arguments: [% base_dir %]/configure.pl "\$(Build.SourceBranchName)"
    workingDirectory: "\$(Build.SourcesDirectory)"
- task: BatchScript@1
  displayName:  Build package
  inputs:
    filename: '[% base_dir %]/build.cmd'
[%- END %]


